- ros_topic_name: "/conveyor/cmd_vel"
  gz_topic_name: "/model/conveyor/link/base_link/track_cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# - ros_topic_name: "/conveyor/status"
#   gz_topic_name: "/model/conveyor/link/base_link/track_cmd_vel"
#   ros_type_name: "std_msgs/msg/Float64"
#   gz_type_name: "gz.msgs.Double"
#   direction: GZ_TO_ROS